import { metrics, profile, projects, publications, recognition, software, timeline } from "../data/content";

const Arrow = () => <span aria-hidden="true">↗</span>;
function SectionHeading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}) { return <header className="section-head"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</header> }

export default function Home() {
 const flagship=projects[0], secondary=projects.slice(1,4), research=projects.slice(4);
 const jsonLd={"@context":"https://schema.org","@type":"Person",name:profile.fullName,jobTitle:"Биотехнолог и разработчик научного программного обеспечения",alumniOf:{"@type":"CollegeOrUniversity",name:"Уральский федеральный университет"},knowsAbout:["3D-культивирование клеток","вирусология","компьютерное зрение","научное программное обеспечение"]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
 <header className="site-header"><a className="brand" href="#top" aria-label="В начало"><span>ИИ</span><b>Иван Иващенко</b></a><nav aria-label="Основная навигация"><a href="#projects">Проекты</a><a href="#publications">Публикации и разработки</a><a href="#experience">Опыт</a><a href="#about">Обо мне</a><a href="#contacts">Контакты</a></nav><details className="mobile-nav"><summary aria-label="Открыть меню">Меню</summary><div><a href="#projects">Проекты</a><a href="#publications">Публикации и разработки</a><a href="#experience">Опыт</a><a href="#about">Обо мне</a><a href="#contacts">Контакты</a></div></details></header>
 <main id="top">
  <section className="hero"><div className="hero-copy"><p className="kicker">Исследователь · Екатеринбург</p><h1><span>Иван</span> Иващенко</h1><p className="role">{profile.role}</p><p className="lead">{profile.lead}</p><div className="actions"><a className="button primary" href="#projects">Смотреть проекты <Arrow/></a><a className="button" href="#publications">Публикации и разработки</a><a className="text-link" href="#contacts">Связаться ↓</a></div></div><div className="well-visual" role="img" aria-label="Абстрактная схема 96-луночной платформы"><div className="plate">{Array.from({length:48},(_,i)=><i key={i}/>)}</div><div className="visual-note"><span>3D CELL PLATFORM</span><b>96</b><small>стандартизированный формат</small></div></div></section>
  <section className="trajectory"><p>Клеточная биология</p><i>→</i><p>3D-модели</p><i>→</i><p>Вирусология</p><i>→</i><p>Компьютерное зрение</p><i>→</i><p>Автоматизация</p></section>
  <section className="metrics" aria-label="Подтвержденные показатели">{metrics.map(([n,t])=><div key={t}><strong>{n}</strong><span>{t}</span></div>)}<p>Результаты исследований и разработок с различной ролью автора — от исполнителя до руководителя проекта.</p></section>
  <section id="projects" className="section"><SectionHeading eyebrow="01 · Проекты" title="От клеточной модели — к проверяемому решению" copy="Одна исследовательская линия связывает эксперимент, инженерный прототип и программный анализ данных."/>
   <article className="flagship"><div className="flag-top"><span>{flagship.label}</span><span>01 / 06</span></div><div className="flag-grid"><div><h3>{flagship.title}</h3><p className="large">{flagship.summary}</p><a className="inline" href="#platform-detail">Разобрать систему ↓</a></div><div className="pipeline"><b>мастер-форма</b><i/><b>микролунка</b><i/><b>сфероид</b><i/><b>анализ</b></div></div><div id="platform-detail" className="detail-grid"><div><small>Задача</small><p>{flagship.problem}</p></div><div><small>Мой вклад</small><p>{flagship.contribution}</p></div><div><small>Методы</small><ul>{flagship.methods.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>Подтверждённые результаты</small><ul>{flagship.results.map(x=><li key={x}>{x}</li>)}</ul></div></div><p className="status">{flagship.status}</p></article>
   <div className="project-grid">{secondary.map((p,i)=><article className={`project-card p${i}`} key={p.id} id={p.id}><div><span>{p.label}</span><b>0{i+2}</b></div><h3>{p.title}</h3><p>{p.summary}</p><details><summary>Подробнее</summary><dl><dt>Задача</dt><dd>{p.problem}</dd><dt>Вклад</dt><dd>{p.contribution}</dd><dt>Статус</dt><dd>{p.status}</dd></dl></details><div className="tags">{p.methods.map(x=><span key={x}>{x}</span>)}</div></article>)}</div>
   <h3 className="subhead">Дополнительные исследовательские направления</h3><div className="research-list">{research.map(p=><article key={p.id}><span>{p.label}</span><h3>{p.title}</h3><p>{p.summary}</p><small>{p.status}</small></article>)}</div>
  </section>
  <section id="publications" className="section ink"><SectionHeading eyebrow="02 · Подтверждение" title="Публикации, патенты и программные разработки" copy="Библиография и интеллектуальная собственность ссылаются на проекты, а не повторяют их описание."/>
   <div className="pub-layout"><div><h3>Избранные публикации и доклады</h3>{publications.map(p=><article className="pub" key={p.title}><time>{p.year}</time><div><h4>{p.title}</h4><p>{p.meta}</p><a href={`#${p.project}`}>Связанный проект →</a></div></article>)}</div><div className="patent-stack"><aside className="patent"><span>Патент РФ</span><b>RU 2847666</b><h3>Способ культивирования вируса простого герпеса в сфероидах клеточной культуры лёгкого эмбриона человека (ЛЭЧ-3)</h3><p>Дата выдачи: 15 октября 2025 года</p><a href="#projects">Связан с 3D-платформой →</a></aside><aside className="patent"><span>Патент РФ</span><b>RU 2865846</b><h3>Способ культивирования единичных сфероидов клеток ЛЭЧ-3 в 96-луночном планшете</h3><p>Дата государственной регистрации: 10 июля 2026 года</p><a href="#projects">Связан с 3D-платформой →</a></aside></div></div>
   <div className="software"><div><p className="eyebrow">12 регистраций</p><h3>Программы для ЭВМ</h3><p>Компактная система по назначению — без ложного равенства масштаба.</p></div>{software.map(group=><div key={group[0]}><h4>{group[0]}</h4><ul>{group.slice(1).map(x=><li key={x}>{x}</li>)}</ul></div>)}</div>
  </section>
  <section id="experience" className="section"><SectionHeading eyebrow="03 · Опыт" title="Исследовательская траектория"/><div className="experience-grid"><div className="timeline">{timeline.map(([y,t])=><div key={y+t}><time>{y}</time><p>{t}</p></div>)}</div><div className="recognition"><h3>Финансирование, программы и обмен опытом</h3>{recognition.map(([type,text])=><div key={text}><span>{type}</span><p>{text}</p></div>)}</div></div></section>
  <section id="about" className="section about"><p className="eyebrow">04 · Обо мне</p><blockquote>«Воспроизводимый эксперимент начинается не с красивого результата, а с понятного процесса».</blockquote><div><p>{profile.about}</p><p>Основная смысловая линия работы: 3D-клеточные модели → превентивная медицина → доклинический скрининг → снижение риска неэффективных решений → технологический суверенитет.</p></div></section>
  <section id="contacts" className="contact"><p className="eyebrow">05 · Контакты</p><h2>Открыт к исследовательскому сотрудничеству и задачам научного ПО.</h2><p>Публичные контактные данные будут добавлены после подтверждения. Пока познакомиться с работой можно через проекты и публикации на этом сайте.</p><a className="button light" href="#top">Вернуться к началу ↑</a></section>
 </main><footer><b>{profile.name}</b><span>Биотехнолог · исследователь · разработчик</span><span>© 2026</span></footer></>;
}
